try:
    my_int = int("a")
except ValueError:
    print("erorr catch")
